POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "test12345556",
    "number": "028"
}

###
POST https://bizley-phonebook.fly.dev/api/persons
content-type: application/json

{
    "name": "test",
    "number": "028"
}